# Generated by Django 2.1.3 on 2018-11-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('duration', models.CharField(max_length=250)),
                ('ratings', models.IntegerField()),
                ('language', models.CharField(max_length=250)),
                ('poster', models.CharField(max_length=600)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Director')),
                ('genre', models.ManyToManyField(to='movie.Genre')),
            ],
        ),
    ]
